title: <p align="center"> Jennifer Nguyen </p> 


logo: "/assets/img/Thuy_Nguyen.jpg?raw=true"


description: 
<p align="center">
  <a href="https://drive.google.com/file/d/12lkPN04UPCNZOxJl7se4Kpi6OVLsY1ZA/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/thuy-jennifer-nguyen/">LinkedIn</a> |
  <a href="https://github.com/jennifernguyen281">GitHub</a>
  </p>
  
  
  <p align="justify">
  I deliver actionable data insights to support business decision-making through analytics. <br> 
  MS in Business Analytics at George Washington University
  <br><br>
  </p>

theme: jekyll-theme-minimal
