title: Jennifer Nguyen


logo: /assets/img/Thuy_Nguyen.jpg


description: 
<p align="center">
  <a href="https://drive.google.com/file/d/12lkPN04UPCNZOxJl7se4Kpi6OVLsY1ZA/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/thuy-jennifer-nguyen/">LinkedIn</a> |
  <a href="https://github.com/jennifernguyen281">GitHub</a>
  </p>
  
  
  <p align="justify">
  I deliver actionable data insights to support business decision-making through descriptive and predictive analytics. <br> 
  Currently pursuing an MS in Data Science at NYU Center for Data Science, my goal is to attain mastery over data science to translate consumer insights into data-intensive product solutions. 
  <br><br>
  </p>

theme: jekyll-theme-minimal
